### ISSUE TITLE
didn't call onProduce

### ISSUE THREAD

**Issue by DinuNuta** [ethand91/mediasoup-ios-client#30]
Didn't call onProduce when i'm cal transport.produce

**Comment by ethand91** [comment]
This may have been fixed in version 1.3.5, could you try it?

**Comment by DinuNuta** [comment]
I tried it on v 1.3.5 it still not call onProduce 
try to create produce : transport.produce(producerHandler, track: videotrack, encodings: nil, codecOptions: codecOptions)
flow onConnect -> sent event connectWebRtcTransport to signal server -> received success
but not call onProduce delegate 
Thanks a lot!

**Comment by ethand91** [comment]
Can you share the logs?
Are you getting the produce response from the mediasoup server?

**Comment by DinuNuta** [comment]
"Are you getting the produce response from the mediasoup server?" NO
for send produce event should receive local onProduce in SendTransport delegate 
it stopped here
logs:
`createVideoTrack() got device count = 1
createVideoTrack() use device <AVCaptureFigVideoDevice: 0x102969270 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]>
createProducer = [:]
videoView(_:didChangeVideoSize:)
(360.0, 480.0)
(194.0, 354.0, 90.0, 120.0)
onConnect(_:dtlsParameters:)
<SendTransport: 0x283631d00>
fed779c4-66ea-4d4f-ac6f-8016780283bb
##############################################
Emiting: connectWebRtcTransport
["data": ["dtlsParameters": {
    fingerprints =     (
                {
            algorithm = "sha-256";
            value = "35:3C:80:39:84:56:1E:AB:5B:1B:6C:1A:4E:48:FD:82:1C:71:6C:4F:2E:EB:E3:0C:A7:42:DC:52:41:54:03:5F";
        }
    );
    role = server;
}, "transportId": "fed779c4-66ea-4d4f-ac6f-8016780283bb"], "event": "connectWebRtcTransport"]
[

]
[]
onConnectionStateChange(_:connectionState:)checking`

![Screen Shot 2020-05-27 at 11 36 44](https://user-images.githubusercontent.com/22508915/82997219-c26b0000-a00e-11ea-8b53-79cfb3839676.png)
Thanks!

**Comment by ethand91** [comment]
Is the video track created shown on the screen?

**Comment by DinuNuta** [comment]
Yes video is displayed.
It's happening also when create produce only audio track, and try to RecvTransport.consume(

**Comment by ethand91** [comment]
Does the below sample work?
https://github.com/ethand91/mediasoup-ios-client-sample

I can't reproduce this.

**Comment by DinuNuta** [comment]
Thanks !
I solved this with the implemented internal SendTransportHandler, but immediately after create producer catch in onConnectionStateChange(_:connectionState:) state failed.
What could be?

**Comment by ethand91** [comment]
Have you configured your mediasoup server transport ip to the ip of the server?
Do any error logs show up?
You could also try enabling logs on the mediasoup server instance.

**Comment by DinuNuta** [comment]
I setted ip of the server, but i am catching error on connect more then one consumer:
"Terminating app due to uncaught exception 'RuntimeException', reason: 'Failed to set remote offer sdp: Duplicate a=mid value '1'.'"
What could be?
Thanks!

**Comment by ethand91** [comment]
Does it work if connect is run synchronously?

**Comment by DinuNuta** [comment]
This happen every time when consume more than 2 consumers

**Comment by ethand91** [comment]
duplicate of https://github.com/ethand91/mediasoup-ios-client/issues/35
